export const DISPLAY_STUDENT = "DISPLAY_STUDENT";
export const ADD_STUDENT = "ADD_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";
export const EDIT_STUDENT = "EDIT_STUDENT";
export const PAGE_MANAGE="PAGE_MANAGE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";

export const ADD_PARENT = "ADD_PARENT";
export const EDIT_PARENT = "EDIT_PARENT";
export const REQ_DISPLAY_PARENT = "REQ_DISPLAY_PARENT";
export const REQ_DISPLAY_PARENT_CLOSE = "REQ_DISPLAY_PARENT_CLOSE";
export const DISPLAY_PARENT = "DISPLAY_PARENT";
export const IMPORT_PARENT_START = "IMPORT_PARENT_START";
export const IMPORT_PARENT_FINISH = "IMPORT_PARENT_FINISH";

export const ADD_CHILDREN = "ADD_CHILDREN";
export const EDIT_CHILDREN = "EDIT_CHILDREN";
export const REQ_DISPLAY_CHILDREN = "REQ_DISPLAY_CHILDREN";
export const REQ_DISPLAY_CHILDREN_CLOSE = "REQ_DISPLAY_CHILDREN_CLOSE";
export const DELETE_CHILDREN = "DELETE_CHILDREN";
export const DISPLAY_CHILDREN = "DISPLAY_CHILDREN";
export const IMPORT_CHILDREN_START = "IMPORT_CHILDREN_START";
export const IMPORT_CHILDREN_FINISH = "IMPORT_CHILDREN_FINISH";

export const ADD_TIMESLOT = "ADD_TIMESLOT";
export const REQ_DISPLAY_TIMESLOT = "REQ_DISPLAY_TIMESLOT";
export const REQ_DISPLAY_TIMESLOT_CLOSE = "REQ_DISPLAY_TIMESLOT_CLOSE";
export const DISPLAY_TIMESLOT = "DISPLAY_TIMESLOT";
export const IMPORT_TIMESLOT_START = "IMPORT_TIMESLOT_START";
export const IMPORT_TIMESLOT_FINISH = "IMPORT_TIMESLOT_FINISH";

export const ADD_APPOINTMENT = "ADD_APPOINTMENT";
export const EDIT_APPOINTMENT = "EDIT_APPOINTMENT";
export const REQ_DISPLAY_APPOINTMENT = "REQ_DISPLAY_APPOINTMENT";
export const REQ_DISPLAY_APPOINTMENT_CLOSE = "REQ_DISPLAY_APPOINTMENT_CLOSE";
export const DISPLAY_APPOINTMENT = "DISPLAY_APPOINTMENT";
export const FILTER_APPOINTMENT = "FILTER_APPOINTMENT";
export const FILTER_APPOINTMENT_CANCEL = "FILTER_APPOINTMENT_CANCEL";
export const GET_CUSTOMER_APPOINTMENT = "GET_CUSTOMER_APPOINTMENT";

export const REQ_DISPLAY_CATCH = "REQ_DISPLAY_CATCH";
export const REQ_DISPLAY_CATCH_CLOSE = "REQ_DISPLAY_CATCH_CLOSE";
export const DISPLAY_REQ_CATCH = "DISPLAY_REQ_CATCH";
export const EDIT_REQ_CATCH = "EDIT_REQ_CATCH";

export const ADD_DUE_INVOICE = "ADD_DUE_INVOICE";
export const REQ_DISPLAY_DUE_INVOICE = "REQ_DISPLAY_DUE_INVOICE";
export const REQ_DISPLAY_DUE_INVOICE_CLOSE = "REQ_DISPLAY_DUE_INVOICE_CLOSE";
export const DISPLAY_DUE_INVOICE = "DISPLAY_DUE_INVOICE";
export const GET_CUSTOMER_FOR_DUE = "GET_CUSTOMER_FOR_DUE";
export const EDIT_DUE_INVOICE = "EDIT_DUE_INVOICE";

export const REQ_DISPLAY_NOTIFICATION = "REQ_DISPLAY_NOTIFICATION";
export const REQ_DISPLAY_NOTIFICATION_CLOSE = "REQ_DISPLAY_NOTIFICATION_CLOSE";
export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const DISPLAY_NOTIFICATION = "DISPLAY_NOTIFICATION";

export const FCM_TOKEN_REQUEST = "FCM_TOKEN_REQUEST";

export const REQ_DISPLAY_UNIFORM_REQUEST = "REQ_DISPLAY_UNIFORM_REQUEST";
export const REQ_DISPLAY_UNIFORM_REQUEST_CLOSE = "REQ_DISPLAY_UNIFORM_REQUEST_CLOSE";
export const DISPLAY_UNIFORM_REQUEST = "DISPLAY_UNIFORM_REQUEST";

export const NOTIFICATION_CLICK = "NOTIFICATION_CLICK";
export const TOTAL_NOTIFICATION_COUNT = "TOTAL_NOTIFICATION_COUNT";
export const TOTAL_UNIFORM_NOTI_COUNT = "TOTAL_UNIFORM_NOTI_COUNT";
export const TOTAL_REQ_CATCH_NOTI_COUNT = "TOTAL_REQ_CATCH_NOTI_COUNT";